### ISSUE TITLE
No way to add a bytestream via `.add()`

### ISSUE THREAD

**Issue by pjz** [ipfs/py-ipfs-api#111]
`.add()` requires a filename be passed to it - there's no way to pass in just a bunch of data.  I guess I should write the data to a tempfile and pass that filename in?  ick.

**Comment by whereswaldon** [comment]
You're right, it would be nice if there was an alternate way to do that. Would you like to take a stab at writing it?

**Comment by rddaz2013** [comment]
"just a bunch of data" for ipfs it has to be a 'solid' file - because of the hashing. If it it only a tempfile nobody can fetch the data per hash - anymore.  If you got 'fire-and-forget' data use the new pubsub feature to send a data into a channel.

Don't know if py-ipfs has already the pubsub feature.....?

**Comment by pjz** [comment]
@whereswaldon not at the moment, sorry; I'm trying to get some other IPFS services limping.  Later, maybe.

**Comment by alexander255** [comment]
This has been possible [for a long time](https://github.com/ipfs/py-ipfs-api/commit/9f0499aa721416afb50025c595886a188fa20d0f) using the `add_bytes` method. Closing.
