### ISSUE TITLE
Timeout for getting files from IPFS

### ISSUE THREAD

**Issue by chorig9** [ipfs/py-ipfs-api#129]
Hi,

Is there any way to specify timeout for methods like cat()/get() or any other way to handle calls to this functions with hash to non-existing resource?

Thanks

**Comment by whereswaldon** [comment]
As far as I am aware, the underlying IPFS doesn't have support for that, so you'll need to look into options in Python. You may be able to run your `client.get('whatever')` in a cancellable context though. Something like [this](https://stackoverflow.com/a/31667005/7106084) might work for you, but I haven't needed to do it myself.

**Comment by zbyte64** [comment]
Using signals and threads wont work, and shouldn't be done anyways. There isn't a timeout context I could find, looks like the `request` method should pass along kwargs to support this...

**Comment by alexander255** [comment]
@zbyte64: Please note that the use of requests is considered an implementation detail and will likely be augmented by another backend, `aiohttp`, in the future (if I ever get around to fixing the final issues with that). Hence passing arbitrary args to requests has been removed in the 0.4.x transition iirc.

That being said: Since you definitely have a point through that the timeout parameter would be useful, we would gladly accept a patch that adds this.
The required changes for this are pretty trivial: Just add the parameter to the `download`, `request` & `_request` functions of [`ipfsapi.http.HTTPClient`](https://github.com/ipfs/py-ipfs-api/blob/3c2d8f67ec934efae3ea11286ab5ae20fef9b50b/ipfsapi/http.py#L124) and ensure that they are then subsequently end up being passed to the `_do_request` method (which then invokes the `requests` library). Unit tests would be appreciated.

**Comment by AliabbasMerchant** [comment]
I am trying to solve this issue.  
The timeout problem has been solved and the tests are running properly.  
However, when I run `tox`, it halts at the `test_file_chunks` of multipart.py, even though I have not changed the `multipart.py` file.
Also, `tox -e codestyle` raises an `InvocationError` for flake8.exe  

Note: I am using Windows10

**Comment by dentiny** [comment]
Have someone ever solved this problem? I uploaded a txt file and my friend tried to download it. It still took 20 minutes even we were in the same room!

**Comment by alexander255** [comment]
@dentiny: That has nothing to do with this issue. The timeout would only result in you getting a timeout error message instead of plain nothing, but the file wouldn't arrive more quickly because of that.

**Comment by mdmoreno** [comment]
What's the status on this topic? It seems like there's a branch with it finished, but it's not in master...
The unit test was ready if I'm not wrong so... Is there anything I could help with? or is it ready for release?

**Comment by alexander255** [comment]
@mdmoreno: The branch your referring to contains the follow-up library for `py-ipfs-api` that has been in the works for the last couple of months called `py-ipfs-http-client` and is almost done. Of course, I wanted to use the chance of a breaking change (a rename) to also do some other changes as well but it's taken a lot longer than expected (of course). I'll let you know if there is anything that I need help with.

You can check the current status on the new library here: https://github.com/ipfs/py-ipfs-api/milestone/1

**Comment by alexander255** [comment]
Update: `py-ipfs-http-client` has been released last week and includes this feature.
