### ISSUE TITLE
Getting connectionpool error 

### ISSUE THREAD

**Issue by warkechetan** [ipfs/py-ipfs-api#179]
ipfsapi.connect(""localhost,5001)
ipfsapi.exceptions.ConnectionError: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/v0/version?stream-channels=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021FE5D1CCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

**Comment by alexander255** [comment]
Weird, are you sure the error message says `…, port=5000)…` and not `…, port=5001)…` and that you used `ipfsapi.connect("localhost", 5001)` not `ipfsapi.connect("localhost", 5000)`? Please confirm that this wasn't caused by a typo on your side or close the issue if it was.
(You should not need to provide a port at all for this common case, by the way, just plain `ipfsapi.connect()` should also work.)

**Comment by warkechetan** [comment]
> Weird, are you sure the error message says `…, port=5000)…` and not `…, port=5001)…` and that you used `ipfsapi.connect("localhost", 5001)` not `ipfsapi.connect("localhost", 5000)`? Please confirm that this wasn't caused by a typo on your side or close the issue if it was.
> (You should not need to provide a port at all for this common case, by the way, just plain `ipfsapi.connect()` should also work.)
 
I did that i removed "localhost", 5001 and used ipfsapi.connect() still giving error 
ipfsapi.exceptions.ConnectionError: ConnectionError: HTTPConnectionPool(host='localhost', port=5001): Max retries exceeded with url: /api/v0/version?stream-channels=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029A4B61BD68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

**Comment by alexander255** [comment]
Are you able to open http://localhost:5001/ (or whatever the target port is) in you web browser? It should result in a blank page with the words *404 page not found*. It you get a connection error in the web browser as well then the problem is elsewhere, “actively refused” sounds like a Firewall issue to me anyways.
Hopefully we can figure things out.

**Comment by warkechetan** [comment]
> Are you able to open http://localhost:5001/ (or whatever the target port is) in you web browser? It should result in a blank page with the words _404 page not found_. It you get a connection error in the web browser as well then the problem is elsewhere, “actively refused” sounds like a Firewall issue to me anyways.
> Hopefully we can figure things out.

Thanks for help i dont used command ipfs daemon.It starts 5001 port.

**Comment by Skyge** [comment]
@alexander255 I meet a similar problem, 
`
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipfs.infura.io', port=5001): Max retries exceeded with url: /api/v0/version?stream-channels=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2feb537b70>: Failed to establish a new connection: [Errno 111] Connection refused'))
`
It seems like I can not connect to the ipfs. Any idea?

**Comment by alexander255** [comment]
@Skyge: I may be wrong, but `ipfs.infura.io` provides an IPFS *gateway*, not the whole IPFS *API*. If so, then *py-ipfs-api*/*py-ipfs-http-client* will not help you as it is used for managing an IPFS instance you own, not just for downloading content (which it can do too, but that's more of a side-effect from exposing the daemon API).

In short:
  * If you only wish to *download* content from a public (or local) IPFS *gateway* just use `aiohttp` or `requests` – no need for *py-ipfs-http-client*
  * If you wish to *manage* a local IPFS *node* use *py-ipfs-http-client*

Does this short explanation sound useful to you @Skyge? Do you think this would be useful to put in the README?

**Comment by Skyge** [comment]
@alexander255 Yeah, you really make a clearly explaining, I mix up *IPFS gateway* and  *IPFS API*, I will have a try following your advice.
