### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by puilp0502** [ipfs/py-ipfs-api#83]
[The documentation link](https://ipfs.io/ipns/QmZ86ow1byeyhNRJEatWxGPJKcnQKG7s51MtbHdxxUddTH/Software/Python/ipfsapi/) in README seems to be down. 
Could this be ipns related? Gateway says "Could not resolve name".

**Comment by whereswaldon** [comment]
@puilp0502 I suspect that the node hosting that IPNS address is down, but I'm not actually sure where that node is hosted. If you have make and sphinx available, you could generate a copy from the `docs` directory with `make html`.

@alexander255 Is the IPNS link that we provide in the README from your personal IPFS node, or from something cloud-based?

**Comment by puilp0502** [comment]
@whereswaldon Thanks!
In case of someone looking for docs stumbling upon this issue, I added documentations as of 33e3ce1 [here](https://ipfs.io/ipfs/QmdxmAVNCJ4RQJquoTxTfi2p51damA3HfxCUyBHcMdJJ85/).

**Comment by whereswaldon** [comment]
Since this is resolved, I'm going to close it. Thanks for putting the docs up!
@alexander255 Have you seen the above?

**Comment by alexander255** [comment]
Yup, I've seen, fixed and immediately forgotten about the above 😕
Sorry about that, stuff like that really shouldn't happen!

Regarding your original question:

> Is the IPNS link that we provide in the README from your personal IPFS node, or from something cloud-based?

Both, it's a VPS that runs a hand-crafted cron-job which re-exports the files from my personal IPFS node. I do not quite remember what the problem back then was, but I've set up web monitoring of the docs through an external monitoring service and I there have been no major outages since, it is therefor solved yes.

**Comment by whereswaldon** [comment]
Okay, thank you!
