### ISSUE TITLE
ipfs shutdown support

### ISSUE THREAD

**Issue by machawk1** [ipfs/py-ipfs-api#99]
go-ipfs v0.4.10 introduced the `ipfs shutdown` directive to more gracefully kill the IPFS daemon instead of CTRL-C or killing the PID (or in ipwb, `killall ipfs`). It would be [much preferred](https://github.com/oduwsdl/ipwb/issues/236) to use the ipfs-api module to accomplish this but no `ipfsapi.shutdown()` is implemented as far as I can tell, as the API is currently aligned with go-ipfs v0.4.9 per the README.

Is there a way to pass ipfsapi an arbitrary command to relay to the ipfs daemon if py-ipfs-api does not yet support it? If not, that would be a nice feature to have to account for the lag in the API to the daemon implementation.

Are there plans to update the py-ipfs-api to the new features in go-ipfs 0.4.10? The above more graceful shutdown would be handy.

**Comment by alexander255** [comment]
Hi and thanks for the feedback!

Sending arbitrary commands is indeed only possible using the (largely undocumented) internal API. This should do the trick for now however (API stablility on this not guaranteed beyond the next minor version):

```py
c = ipfsapi.connect()
# … Run app …
c._client.request('/shutdown')
```

Since there is such [a nice update](https://ipfs.io/blog/27-go-ipfs-0-4-10/) on what changed in v0.4.10, I'll be updating the library quite soon through. 🙂
